# .github/workflows/destroy.yml
name: "Terraform Destroy Infrastructure"

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "DESTROY" to confirm'
        required: true

env:
  AWS_REGION: eu-west-2
  AWS_ROLE_ARN: arn:aws:iam::436549840164:role/github_action_role
  TF_VERSION: "1.5.0"
  TF_LOG: INFO

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'DESTROY'
    
    defaults:
      run:
        working-directory: Infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan Destroy
        id: plan
        run: terraform plan -destroy -no-color -input=false
        continue-on-error: true

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
